apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeware-provider.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeware-provider.labels" . | nindent 4 }}
  {{- if eq .Values.monitoring.agent "prometheus.io/builtin" }}
  annotations:
    prometheus.io/scrape: "true"
    {{- if .Values.monitoring.operator }}
    prometheus.io/operator_path: "/metrics"
    prometheus.io/operator_port: "8443"
    prometheus.io/operator_scheme: "https"
    {{- end }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: webhook-server
    {{- include "kubeware-provider.selectorLabels" . | nindent 4 }}
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
