{{- if .Values.apiserver.enableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubeware-provider.fullname" . }}
  labels:
    {{- include "kubeware-provider.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubeware-provider.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-kubeware-dev-v1-clusterbinding
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: clusterbindings.kubeware.dev
    rules:
      - apiGroups:
          - kubeware.dev
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterbindings
    sideEffects: None
{{ end }}
