apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeware-server.fullname" . }}
  labels:
    {{- include "kubeware-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kubeware-server.appscode.com
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - kubedb.com
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups:
  - kubevault.com
  resources: ["*"]
  verbs: ["get", "list", "watch"]
