project:
  name: Kubeware Backend Server by AppsCode
  shortName: Kubeware Backend Server
  url: https://github.com/kubeware/kubeware-server
  description: Kubeware Backend Server for Kubernetes
  app: a Kubeware Backend Server
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kubeware-server
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.21+
release:
  name: kubeware-server
  namespace: kubeops
