project:
  name: kube-bind Server by AppsCode
  shortName: kube-bind Server
  url: https://github.com/kubeware/kube-bind-server
  description: kube-bind Server for Kubernetes
  app: a kube-bind Server
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kubeware-service-provider
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.21+
release:
  name: kubeware-service-provider
  namespace: kubeops
