apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeware-service-provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeware-service-provider.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubeware-service-provider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubeware-service-provider.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "appscode.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "kubeware-service-provider.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.image.securityContext | nindent 12 }}
{{/*          image: {{ include "image.registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}*/}}
          image: superm4n/kube-bind-server:config_linux_amd64
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - provider
            - --namespace-prefix={{ .Values.provider.namespacePrefix }}
            - --pretty-name={{ .Values.provider.providerPrettyName }}
            - --consumer-scope={{ .Values.provider.consumerScope }}
            - --external-address={{ .Values.provider.external.address }}
            - --external-ca-file={{ .Values.provider.external.CAFile }}
            - --external-server-name={{ .Values.provider.external.serverName }}
{{/*            - --subject=*/}}
{{/*            - --cluster-id=*/}}
{{/*            - --group=*/}}
{{/*            - --resource=*/}}
{{/*            - --kubeconfig="/.kube/config"*/}}
{{/*            - --namespace=*/}}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.image.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
